# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ordersomewaiter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ordersomewaiter
  pod 'Firebase/Core', '~> 5.6.0'
  pod 'Firebase/Messaging', '~> 5.6.0'
  
end

