export const NO_NETWORK_CONNECTION = 'NO_NETWORK_CONNECTION';
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
export const TOO_MANY_RESTAURANTS = 'TOO_MANY_RESTAURANTS';
export const RESTAURANT_PICKED_AND_LOADED = 'RESTAURANT_PICKED_AND_LOADED';
export const ERROR_LOGGING_IN = 'ERROR_LOGGING_IN';
